### ISSUE TITLE
Allow disabling checksum test for zlib

### ISSUE THREAD

**Issue by HeroicKatora** [Frommi/miniz_oxide#102]
This is a feature request, motivated by the request to parse a `png` with incorrect checksum

> libpng warning: IDAT: incorrect data check

The `png` library _also_ wants to accept this image as it [obviously has correct image data](https://github.com/image-rs/image-png/issues/294) and the need for actually checksumming data chunks at rest is dubious at best. It seems that `miniz_oxide` currently _always_ computes and tests the checksum when the flag `TINFL_FLAG_PARSE_ZLIB_HEADER` is active.

https://docs.rs/miniz_oxide/0.4.4/src/miniz_oxide/inflate/core.rs.html#1619

I had previously assumed that not setting `TINFL_FLAG_COMPUTE_ADLER32` would work but counter intuitively it seems that it the flag is overwritten by the zlib request.

**Comment by oyvindln** [comment]
Yeah this seems reasonable. png actually has double checksums for the sections I think? Using both the zlib one and a CRC checksum in the png format itself, so one could probably save some processing by skipping the zlib one.
