### ISSUE TITLE
Cannot build in `-Z build-std` with `#![no_std]`

### ISSUE THREAD

**Issue by nbdd0121** [Frommi/miniz_oxide#106]
I tried to depend on `miniz_oxide` on a `#![no_std]` crate with `-Z build-std` option used for buidling. However `miniz_oxide` will depend on `std` instead of `alloc` due to cuviper/autocfg#34.

Perhaps it'll be better to detect presence of alloc by rust version instead?

**Comment by oyvindln** [comment]
Ok, I've now removed autocfg entirely, MSRV is bumped to 1.40 rather than 1.36 to also be able to use non_exhaustive.

**Comment by nbdd0121** [comment]
I can confirm that it's fixed.
