### ISSUE TITLE
Bug in decompression.

### ISSUE THREAD

**Issue by Frommi** [Frommi/miniz_oxide#12]
Cargo built with `miniz_oxide` panics while unpacking `clfft v0.3.1` package from crates.io. Found this bug using brand new [tester](https://github.com/Frommi/miniz_oxide_tester).

**Comment by Frommi** [comment]
Reproduction:
- run `cargo build` in [miniz_oxide_tester/cargo](https://github.com/Frommi/miniz_oxide_tester/tree/master/cargo);
- find `cargo` executable in `target`; run `./cargo new`;
- add `clfft = "0.3.1"` to deps in `Carto.toml`;
- `./cargo build`.

**Comment by oyvindln** [comment]
Oh wow, segmentation fault even.

**Comment by oyvindln** [comment]
I found the problem, though it's probably worth investigating why it triggered a segmentation fault after panicking.
