### ISSUE TITLE
Make `DecompressError` implement the `Error` trait

### ISSUE THREAD

**Issue by Shnatsel** [Frommi/miniz_oxide#122]
Right now the `DecompressError` returned by `decompress_to_vec*` family of functions does not implement the [Error](https://doc.rust-lang.org/stable/std/error/trait.Error.html) trait. This makes working with it rather unwieldy, and requires the user to write their own messages for every value of TINFLStatus if they wish to display the error to the user.

**Comment by oyvindln** [comment]
Yeah I left that out for now as I wasn't quite sure how to handle that with no_std etc, but it really should.

**Comment by oyvindln** [comment]
Looks like adding a "std" feature which could or could not be enabled per default might be the best option. Not sure if adding it as a default without a major version bump would be fine or if it should not be default for now.

https://www.reddit.com/r/rust/comments/liv2ib/no_std_with_error_trait/

**Comment by oyvindln** [comment]
Added in c52cf711db0dcf38481c7e5e79d4fd60b09728b5
