### ISSUE TITLE
Crashes 'index 15536 out of range for slice of length 15533'

### ISSUE THREAD

**Issue by sanmai-NL** [Frommi/miniz_oxide#13]
```
  22: std::panic::catch_unwind
             at /checkout/src/libstd/panic.rs:365
  23: mz_inflate
             at /home/sanmai/.cargo/bin/registry/src/github.com-1ecc6299db9ec823/miniz_oxide_c_api-0.1.1/src/lib.rs:104
  24: flate2::mem::Decompress::decompress
             at /home/sanmai/.cargo/bin/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.1/src/mem.rs:368
  25: <flate2::mem::Decompress as flate2::zio::Ops>::run
```

**Comment by Frommi** [comment]
Thanks for the report! A bit more information on the data being decompressed and/or full logs would be appreciated. As is, there is even no "out of range for slice" from title in the logs. If you can run this under valgrind and copy-paste output, that would be very helpful.

**Comment by oyvindln** [comment]
It's possible that this is related to [this](https://github.com/alexcrichton/flate2-rs/issues/142).

**Comment by oyvindln** [comment]
@sanmai-NL Is this fixed by 
0bd8851 ?

**Comment by matklad** [comment]
@oyvindln is miniz-sys used by default by some shidespread libraries? I think I’ve seen several index out of bounds panics during decompression of various things recently. For example, this one: https://ci.appveyor.com/project/DarkEld3r/exonum-sodiumoxide/build/1.0.15/job/rrcxdvl9q5vryrfl#L220

**Comment by matklad** [comment]
Yep, it's used by zip-rs by default now: https://github.com/mvdnes/zip-rs/commit/50b57f4e3711d21dcf2ce18f4cb69cfdf037b158

Might be worthwhile to bump the min version of miniz in flate2 & zip-rs then!

**Comment by FauxFaux** [comment]
I've just hit this issue on the updated crate.

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 32768 but the index is 32768', /home/faux/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.1.2/src/inflate/core.rs:952:25
FATAL ERROR: Caught panic!
zsh: segmentation fault (core dumped)  nice cargo run --release
```

Unfortunately, the segfault took out my error handling, so I have no idea where I hit the problem..

I'm decompressing a known set of non-private files, so I will be able to find it again, assuming it's deterministic. Give me a few tens of CPU hours to get back to where I was...

**Comment by oyvindln** [comment]
It looks like it's a different OOB issue than the one that was fixed in 0bd8851. It's possible the `out_pos` indexes [here](https://github.com/Frommi/miniz_oxide/blob/master/miniz_oxide/src/inflate/core.rs#L950) where the crash happens should be masked like the match source position given that we may have a wrapping buffer.

**Comment by oyvindln** [comment]
>I've just hit this issue on the updated crate.
@FauxFaux Which way was inflate called when you hit this panic, was it through flate2, which uses wrapping output buffers, or using decompress_to_vec, which uses a non-wrapping buffer?

**Comment by FauxFaux** [comment]
The comment above is through flate2. The same file fails in #19 with `decompress_to_vec`, though. So, both!

**Comment by sanmai-NL** [comment]
@oyvindln: I haven’t encountered errors since your fix. 🙂

**Comment by oyvindln** [comment]
Awesome, marking this as closed then.
