### ISSUE TITLE
miniz_oxide doesn't validate HLIT

### ISSUE THREAD

**Issue by fintelia** [Frommi/miniz_oxide#130]
The deflate spec requires that dynamic blocks contain at most 286 length/literal codes, despite the encoding allowing values up to 288 to be represented:

> We can now define the format of the block:
> 
>  5 Bits: HLIT, # of Literal/Length codes - 257 (257 - 286)
>  5 Bits: HDIST, # of Distance codes - 1        (1 - 32)
>  4 Bits: HCLEN, # of Code Length codes - 4     (4 - 19)

Unfortunately, this crate doesn't validate the requirement when decoding, so blocks with 287 or 288 length/literal codes are also accepted.

[Example file](https://github.com/Frommi/miniz_oxide/files/10095343/bad.zip) (Make sure to extract the zip file and then feed bad.bin into miniz_oxide. GitHub doesn't allow uploading `.bin` files directly.)

**Comment by oyvindln** [comment]
What do zlib and C miniz when given this data? People often expect corrupted/non-conforming stuff to work regardless so if it e.g decompresses in zlib we might want to let it work as well.

**Comment by fintelia** [comment]
I'm not sure about C miniz, but [zlib rejects this case](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/inflate.c#L946) and even [clarified in an issue](https://github.com/madler/zlib/issues/82) that the handling is intentional.

**Comment by oyvindln** [comment]
Okay, then we should also reject it.

**Comment by oyvindln** [comment]
When adding some code for this it looks like the test file has HLIT 2 and HDIST 23 (i.e 259 litlen codes 24 dist codes) so if it's supposed to fail it might be for something else. Does it decode fine with zlib? (miniz_oxide decodes it and seems to be raw deflate not zlib wrapped)

The code seems to already reject inputs with 32 distance codes (in the bogus_data test in inflate/core.rs), would need to craft something with 287 or 288 litlen codes to see if that would be rejected too.

**Comment by fintelia** [comment]
The bad.bin file should be a zlib encoded deflate stream: The first bytes of the file are `78 01 FD E0 01`. The first two are a zlib header and then of the next couple:
```
11111101 11100000 00000001
       1                   BFINAL=Final Block
     10                    BTYPE=Dynamic Huffman Codes
11111                      HLIT=31+257=288
            00000          HDIST=0+1=1
         111             1 HCLEN=4+15=19

**Comment by oyvindln** [comment]
Ah it's probably correct, checked the source now and I was being a doofus and forgetting to change the filename in the test case I made. Will look into it with the right file later.
