### ISSUE TITLE
Some Panics cause segfaults in jemalloc when called from flate2

### ISSUE THREAD

**Issue by oyvindln** [Frommi/miniz_oxide#14]
Ideally we should never panic of course, but there could still be bugs, and if there are, it shouldn't end up in a segfault.
See [this](https://github.com/alexcrichton/flate2-rs/issues/142#issuecomment-356448950)
I've tried with removing no_mangle and extern_c from mz_inflate, so that doesn't seem to be the issue.

**Comment by steveklabnik** [comment]
cross-language panics are UB. https://doc.rust-lang.org/stable/std/panic/fn.catch_unwind.html was designed for this use-case.  Note that https://github.com/rust-lang/rust/pull/46833 also landed fairly recently...

**Comment by Shnatsel** [comment]
Is this what #36 is supposed to fix?

**Comment by oyvindln** [comment]
I don't know if that was background for it, but it may be related yea. It's something that needs to be sorted in either case. Ideally we woulldn't go through the C Api for flate2 (#16). Going through a C API will always require unsafe.

The project got a bit stalled, but I at least want to look into this again. Would be nice to have some more eyes on this though :)

**Comment by oyvindln** [comment]
I couldn't reproduce this with the current code, so this may have been fixed as of now, but I'll do some more testing before closing.

**Comment by oyvindln** [comment]
Closing this for now since the C api is no longer used and I haven't been able to reproduce this.

**Comment by oyvindln** [comment]
Forgot to actually click close..
