### ISSUE TITLE
Missing tags for versions 0.7.1 and 0.7.2

### ISSUE THREAD

**Issue by paolobarbolini** [Frommi/miniz_oxide#149]
Releases 0.7.1 and 0.7.2 haven't been tagged. Could you add them?

You can find out the git commit id from:

* https://docs.rs/crate/miniz_oxide/0.7.1/source/.cargo_vcs_info.json
* https://docs.rs/crate/miniz_oxide/0.7.2/source/.cargo_vcs_info.json

**Comment by oyvindln** [comment]
Sorry, had forgotten to push them.

**Comment by paolobarbolini** [comment]
Thank you. Closing now
