### ISSUE TITLE
Panic when passing a zero-sized output buffer.

### ISSUE THREAD

**Issue by golddranks** [Frommi/miniz_oxide#23]
`miniz_oxide::inflate::core::decompress` will panic if a output buffer of size 0 is passed in. The panic is due to an overflow in core.rs, on line 1020: `out_cur.get_ref().len() - 1`.

It says that "This function shouldn't panic pending any bugs." in the documentation so I presume this is a bug.

**Comment by oyvindln** [comment]
That is indeed a bug, thanks for noticing.
