### ISSUE TITLE
adler32 check in fuzz target interferes with fuzzing

### ISSUE THREAD

**Issue by Shnatsel** [Frommi/miniz_oxide#29]
The fuzz target currently invokes `miniz_oxide` like this:
https://github.com/Frommi/miniz_oxide/blob/01a57125fc0c6ba87629adfa7b3046030f2f347b/fuzz/fuzz_targets/inflate_nonwrapping.rs#L7

It does not seem to disable alder32 checks. Because of checksum verification fuzzers cannot reach the actually interesting decoding code.

Rust fuzzer integration provides special configuration option `fuzzing` which is set when a binary is built with fuzzing instrumentation; you can use it to disable checksums via conditional compilation ([example](https://github.com/Shnatsel/lodepng-rust/commit/22c87dcd99ffbbe78cb85dc9e7f5d90350901892) from lodepng-rust). Alternatively, you can adapt your fuzzing target to set the required configuration parameters to disable checksum verification (inflate crate provides a [*_no_checksum function](https://docs.rs/inflate/0.4.2/inflate/fn.inflate_bytes_zlib_no_checksum.html)).

cc @oyvindln who has authored the fuzz target.

I can also provide you with an initial fuzzing corpus to kickstart fuzzing, both with and without zlib headers, obtained by fuzzing `inflate` crate with afl-fuzz, libfuzzer and honggfuzz. If you're interested, let me know and I'll attach it here.

[honggfuzz-rs](https://github.com/rust-fuzz/honggfuzz-rs) provides further documentation, including enabling sanitizers to catch bugs in code under `unsafe`. Or ping me or https://github.com/rust-fuzz if you have any questions regarding fuzzing.

**Comment by Shnatsel** [comment]
Here are the fuzzing seeds, with and without zlib headers respectively.

[min_starting_points.tar.gz](https://github.com/Frommi/miniz_oxide/files/2147124/min_starting_points.tar.gz)
[nozlib_min_starting_points.tar.gz](https://github.com/Frommi/miniz_oxide/files/2147123/nozlib_min_starting_points.tar.gz)

**Comment by oyvindln** [comment]
Thanks.

As miniz_oxide seems to have made its way into [gecko](https://github.com/mozilla/gecko-dev/tree/0c0ddaa7e859a2b76a56a0e2e9c0de88af166812/third_party/rust/miniz_oxide_c_api), getting a proper fuzzing setup has become even more important.

**Comment by Shnatsel** [comment]
I've disabled  run the existing "inflate_nonwrapping" fuzz target through a total of over 1 billion iterations under afl-fuzz, honggfuzz and cargo-fuzz. That found no panics, crashes or memory leaks, including under address sanitizer. Kudos!

I've opened a pull request to disable alder32 and add the fuzzing seeds to kickstart future fuzzing.

**Comment by oyvindln** [comment]
That sounds promising. Next up we should probably add some more fuzzing targets for different flags and for streaming configuration.
