### ISSUE TITLE
Wasm: stub the libc dependency in miniz_oxide_c_api

### ISSUE THREAD

**Issue by wehlutyk** [Frommi/miniz_oxide#34]
Hi!

I read through #26, and we could add a small hack to stub the left-over libc calls to also be able to compile `miniz_oxide_c_api` to Wasm. This is all following what was done to use libsodium in [alexcrichton/wasm-sodium](https://github.com/alexcrichton/wasm-sodium) (see the [libc-stub](https://github.com/alexcrichton/wasm-sodium/tree/master/libc-stub) folder).

The [wasm32 branch in wehlutyk/miniz_oxide](https://github.com/wehlutyk/miniz_oxide/tree/wasm32) shows that, and it makes compiling `flate2-rs` to wasm32 possible (see [wehlutyk/flate2-rs/tree/wasm32](https://github.com/wehlutyk/flate2-rs/tree/wasm32)). I use it to read compressed pdf files using `lopdf`, all in the browser, and up to now it works like a charm.

Would you accept a PR for this? It would be great as we could then merge the changes for `flate2-rs` and `lopdf` and have them work on wasm32. But seeing as it's a bit of hack I thought you might want to wait till libc gets implementations for wasm32. Then again it's a useful shim in the meantime :)

**Comment by Frommi** [comment]
Looks good, bring it on. Maybe it's a good idea to make a feature `libc_stub` or something to opt-out of libc. I think it can be useful outside of wasm, right?

**Comment by wehlutyk** [comment]
Great!

`libc_stub` feature: I guess, on other targets for which libc isn't yet well defined. In that case it would be nice to enable it on wasm32 by default. Are you thinking

```#[cfg(any(libc_stub, all(target_arch = "wasm32", not(target_os = "emscripten"))))]```

or simply

```#[cfg(libc_stub)]```

with a way to activate it by default on wasm32?

I've been looking around for how to do that (as in [this comment](https://github.com/rust-lang/cargo/issues/1197#issuecomment-268203727) in rust-lang/cargo#1197), but can't seem to find anything. Do you know if that's doable?

**Comment by wehlutyk** [comment]
I think the target-specific enabling of features is indeed not possible yet, so I'd go with option 1.

**Comment by ctjhoa** [comment]
Related issue https://github.com/alexcrichton/flate2-rs/issues/161

**Comment by wehlutyk** [comment]
Thanks for merging! Do you know when the next version bump is planned?

**Comment by Frommi** [comment]
Well, next version bump will be to a 0.2.0 with breaks in API, so I want to cram as much of different changes as possible into it. Hopefully to get API to a 1.0.0 state. This includes e.g. rusty error code handling and pub constants are a bit of a mess right now. Maybe somewhere between 2 weeks and a month?

**Comment by wehlutyk** [comment]
Makes sense :). There's no rush on my side, it's just so I know when I can PR `flate2`.
