### ISSUE TITLE
tinfl_decompress

### ISSUE THREAD

**Issue by Frommi** [Frommi/miniz_oxide#4]
tinfl_decompress is implemented as a coroutine (state machine) and is a bit of a mess. tdefl is divided into functions so I was able to rewrite it function by function and check that nothing broke, but it won't work as straightforward for tinfl.
I propose to write a big match over enum of all the states and at first delegate them to C tinfl_decompress and rewrite them one by one in terms of match arms.

**Comment by oyvindln** [comment]
That sounds like a good approach :+1:

**Comment by oyvindln** [comment]
Holy crap that function took a while to get my head around.

**Comment by Frommi** [comment]
I feel you, man.

**Comment by Frommi** [comment]
Yay.
