### ISSUE TITLE
More than one person should be able to push releases to crates.io

### ISSUE THREAD

**Issue by oyvindln** [Frommi/miniz_oxide#50]
ping @Frommi @matklad

**Comment by Shnatsel** [comment]
Specifically, a release is needed right now to publish important security fixes.

**Comment by matklad** [comment]
Looks like only @Frommi is the owner of crates.io crate. I thought that @oyvindln has publish rights, but looks like this is not the case :( 

Although I don't actively participate in this crate's development anymore, I am willing to act as a back-up maintainer!

**Comment by oyvindln** [comment]
Yeah I was wondering if you had some way to contact them.

**Comment by Frommi** [comment]
I added (invitations send) @oyvindln as an owner to both crates on crates.io.

**Comment by oyvindln** [comment]
Ah, I seem to have totally missed those :)
