### ISSUE TITLE
Travis miniz_tester can't see linux files.

### ISSUE THREAD

**Issue by Frommi** [Frommi/miniz_oxide#6]
https://travis-ci.org/Frommi/miniz_oxide/builds/267227423
It seems that everything builds properly, all the folders contain right files, but
```
../bin/miniz_tester -v a linux-4.8.11
```
doesn't find the files:

`pwd` output: 
```
/home/travis/build/Frommi/miniz_oxide/test_scratch
```
so we are in the right folder.

`ls` output: 
```
linux-4.8.11  linux-4.8.11.tar.xz
```
`ls linux-4.8.11` output: 
```
arch	 crypto		include  kernel       net	      security
block	 Documentation	init	 lib	      README	      sound
certs	 drivers	ipc	 MAINTAINERS  REPORTING-BUGS  tools
COPYING  firmware	Kbuild	 Makefile     samples	      usr
CREDITS  fs		Kconfig  mm	      scripts	      virt
```
so linux is downloaded and extracted properly.

`ls ../bin` output: 
```
example1  example2  example3  example4	example5  example6  miniz_tester
```
so `miniz_tester` is compiled and then it is executed `../bin/miniz_tester -v a linux-4.8.11`, but can't detect files:
```
Total files processed: 0
```

**Comment by matklad** [comment]
FYI, it's possible to wrestle with Travis CI in non-master branch: by default, Travis builds all branches. I usually create a PR to get quick links to the latest build off the branch.

And I honestly have no idea how to debug this, apart from adding `printf`s to the tester itself.
