### ISSUE TITLE
alloc implementation raised MSRV

### ISSUE THREAD

**Issue by Plecra** [Frommi/miniz_oxide#85]
[`zip-rs`](https://github.com/mvdnes/zip-rs) currently has an MSRV of 1.34.0, which is incompatible with the `alloc` crate. Would it be possible to disable it on versions prior to 1.36.0? I'm happy to do the implementation work

**Comment by oyvindln** [comment]
Yeah raising it was an oversight.

#84 does this, I don't know whether that is a satisfactory solution or if there are better ways of doing it.

1.34 is what's in debian stable, so it's reasonable to still be optionally compatible with it if possible.

**Comment by oyvindln** [comment]
Should be fixed by #84 and #95 .
